/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame {
    public int i = 0;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTwoArrow = new javax.swing.JButton();
        btnAddNewPatientRecords = new javax.swing.JButton();
        btnAddDiagnosisInformation = new javax.swing.JButton();
        btnFullHistoryOfThePatient = new javax.swing.JButton();
        btnUpdatePatientRecord = new javax.swing.JButton();
        btnHospitalInformation = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 788));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTwoArrow.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTwoArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/two arrow.png"))); // NOI18N
        btnTwoArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoArrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnTwoArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));

        btnAddNewPatientRecords.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddNewPatientRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/add new patient.png"))); // NOI18N
        btnAddNewPatientRecords.setText("Add New Patient Records");
        btnAddNewPatientRecords.setPreferredSize(new java.awt.Dimension(240, 59));
        btnAddNewPatientRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatientRecordsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewPatientRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        btnAddDiagnosisInformation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddDiagnosisInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/add diag.png"))); // NOI18N
        btnAddDiagnosisInformation.setText("Add Diagnosis Information");
        btnAddDiagnosisInformation.setPreferredSize(new java.awt.Dimension(240, 59));
        btnAddDiagnosisInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiagnosisInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDiagnosisInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        btnFullHistoryOfThePatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnFullHistoryOfThePatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/rsz_history1.png"))); // NOI18N
        btnFullHistoryOfThePatient.setText("Full History Of The Patient");
        btnFullHistoryOfThePatient.setPreferredSize(new java.awt.Dimension(240, 59));
        btnFullHistoryOfThePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullHistoryOfThePatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnFullHistoryOfThePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, -1, -1));

        btnUpdatePatientRecord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdatePatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/rsz_update_details.png"))); // NOI18N
        btnUpdatePatientRecord.setText("Update Patient Record");
        btnUpdatePatientRecord.setPreferredSize(new java.awt.Dimension(240, 59));
        btnUpdatePatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        btnHospitalInformation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHospitalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/rsz_hospital_information.png"))); // NOI18N
        btnHospitalInformation.setText("Hospital Information");
        btnHospitalInformation.setPreferredSize(new java.awt.Dimension(240, 59));
        btnHospitalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospitalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 412, -1, -1));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/exit.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setPreferredSize(new java.awt.Dimension(240, 59));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 489, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnTwoArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoArrowActionPerformed
        // TODO add your handling code here:
        if(i==0){
            btnAddNewPatientRecords.setLocation(90,30);
            btnAddDiagnosisInformation.setLocation(333,30);
            btnFullHistoryOfThePatient.setLocation(576,30);
            btnUpdatePatientRecord.setLocation(819,30);
            btnHospitalInformation.setLocation(1062,30);
            btnLogOut.setLocation(1062,89);
            i = 1;
        }
        else{
            btnAddNewPatientRecords.setLocation(10,107);
            btnAddDiagnosisInformation.setLocation(10,184);
            btnFullHistoryOfThePatient.setLocation(10,261);
            btnUpdatePatientRecord.setLocation(10,338);
            btnHospitalInformation.setLocation(10,415);
            btnLogOut.setLocation(10,490);
            i = 0;
        }
    }//GEN-LAST:event_btnTwoArrowActionPerformed

    private void btnAddNewPatientRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatientRecordsActionPerformed
        // TODO add your handling code here:
        new addNewPatientRecords().setVisible(true);
    }//GEN-LAST:event_btnAddNewPatientRecordsActionPerformed

    private void btnAddDiagnosisInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiagnosisInformationActionPerformed
        // TODO add your handling code here:
        new addDiagnosisInformation().setVisible(true);
    }//GEN-LAST:event_btnAddDiagnosisInformationActionPerformed

    private void btnFullHistoryOfThePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullHistoryOfThePatientActionPerformed
        // TODO add your handling code here:
        new fullHistoryOfThePatient().setVisible(true);
    }//GEN-LAST:event_btnFullHistoryOfThePatientActionPerformed

    private void btnUpdatePatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientRecordActionPerformed
        // TODO add your handling code here:
        new updatePatientRecord().setVisible(true);
    }//GEN-LAST:event_btnUpdatePatientRecordActionPerformed

    private void btnHospitalInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalInformationActionPerformed
        // TODO add your handling code here:
        new hospitalInformation().setVisible(true);
    }//GEN-LAST:event_btnHospitalInformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiagnosisInformation;
    private javax.swing.JButton btnAddNewPatientRecords;
    private javax.swing.JButton btnFullHistoryOfThePatient;
    private javax.swing.JButton btnHospitalInformation;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTwoArrow;
    private javax.swing.JButton btnUpdatePatientRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
